insert into Employee_master(Name,PostId,LocationId,isStatus,companyId)
values(	'Shrukeerti Thakur',	1,	1,	1,	0)
insert into Employee_master(Name,PostId,LocationId,isStatus,companyId)
values(	'Swati Thari',	2,	1,	2,	0)
insert into Employee_master(Name,PostId,LocationId,isStatus,companyId)
values(	'Siddhant Kumar',	2,	4,	1,	0)
insert into Employee_master(Name,PostId,LocationId,isStatus,companyId)
values(	'Irshana Thakur',	3,	3,	1,	0)
insert into Employee_master(Name,PostId,LocationId,isStatus,companyId)
values(	'Indra Thakur',	3,	2,	1,	0)
